name: dualkl
channels:
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.1
  - mkl-devel[version='<2024.1']
  - mkl-include[version='<2024.1']
  - mkl[version='<2024.1']
prefix: /hpc2hdd/home/ychu763/anaconda3/envs/dualkl